version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - java -version
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      - mvn test
  build:
    commands:
      # Build
      - mvn package
  post_build:
    commands:
      - mv target/ExampleJava-0.0.1-SNAPSHOT.jar ExampleJava-0.0.1-SNAPSHOT.jar
      #- zip ExampleJava-0.0.1-SNAPSHOT.zip -ur .ebextensions ExampleJava-0.0.1-SNAPSHOT.jar

artifacts:
  #type: zip
  files:
    - ExampleJava-0.0.1-SNAPSHOT.jar
    - .ebextensions/*